import Vue from "vue";
import { validateData } from "@/utils/validate";
// import { enumApiPlugin } from "@/utils/enumFetch";
// import { enumFetchApi } from "@/utils/enumApiFetch";
import { findByProperty } from "@/utils/util";
// import { exportHandle } from "@/utils/export.js";
// import "@/utils/browserPatch";
Vue.prototype.$validateData = validateData;
Vue.prototype.$findByProperty = findByProperty;
// Vue.prototype.$exportHandle = exportHandle;
// Vue.use(enumApiPlugin);
// Vue.use(enumFetchApi);
